// Generated by supernote_module_generator. Do not edit.
#include "feature_registry.hpp"

#include <array>

namespace supernote::generated {
namespace {

constexpr std::array<FeatureDescriptor, 1> kFeatures{{
    {"supernote:feature:7e680f69f87879eb", "Snfiletools"},
}};

}  // namespace

const FeatureDescriptor *feature_registry_data() noexcept {
  return kFeatures.data();
}

std::size_t feature_registry_size() noexcept {
  return kFeatures.size();
}

}  // namespace supernote::generated
