// Generated by supernote_module_generator. Do not edit.
#pragma once

#include <cstddef>

namespace supernote::generated {

struct FeatureDescriptor {
  const char *feature_id;
  const char *public_name;
};

const FeatureDescriptor *feature_registry_data() noexcept;
std::size_t feature_registry_size() noexcept;

}  // namespace supernote::generated
