// Generated by supernote_module_generator. Do not edit.
#include <jni.h>
#include <jsi/jsi.h>

#include <android/log.h>
#include <ReactCommon/CallInvokerHolder.h>

#include <atomic>
#include <cstdint>
#include <functional>
#include <memory>
#include <mutex>
#include <optional>
#include <stdexcept>
#include <string>
#include <unordered_map>
#include <utility>

#include "runtime_services.hpp"

namespace supernote::generated {
void install_plugin_bindings(
    facebook::jsi::Runtime &runtime,
    const std::shared_ptr<supernote::runtime::RuntimeSession> &runtime_session);
}

extern "C" __attribute__((visibility("hidden"))) jboolean
sn_supernote_runtime_b1ee3d0df6ed_register_natives(
    JNIEnv *env, jobject class_loader, jstring generation_identity);

namespace {

constexpr char kLogTag[] = "SupernoteModuleRuntime";
constexpr char kLoadRequestProperty[] = "supernote.module.load-request.sn_supernote_runtime_b1ee3d0df6ed.v1";
constexpr char kRegistrarProperty[] = "supernote.module.registrar.sn_supernote_runtime_b1ee3d0df6ed.v1";
std::string g_generation_identity;
std::mutex g_mutex;
std::unordered_map<std::uint64_t,
                   std::shared_ptr<supernote::runtime::RuntimeSession>>
    g_sessions;

#if defined(SUPERNOTE_MODULE_WEAK_OBJECT_PROBE)
constexpr char kWeakProbeGlobal[] = "__supernoteModulePhase0WeakObjectProbe";
constexpr char kWeakProbeTargetGlobal[] =
    "__supernoteModulePhase0WeakObjectProbeTarget";

class WeakObjectProbeHost final : public facebook::jsi::HostObject {
 public:
  WeakObjectProbeHost(
      facebook::jsi::Runtime &runtime,
      const facebook::jsi::Object &target) {
    weak_.emplace(runtime, target);
    if (!lock_and_verify(runtime)) {
      throw std::runtime_error("JSI WeakObject could not lock its live target");
    }
    __android_log_print(
        ANDROID_LOG_INFO, kLogTag,
        "phase0 weak object created and locked on JS thread");
  }

  ~WeakObjectProbeHost() override {
    weak_.reset();
    __android_log_print(
        ANDROID_LOG_INFO, kLogTag,
        "phase0 weak object destroyed by runtime-managed HostObject teardown");
  }

  facebook::jsi::Value get(
      facebook::jsi::Runtime &runtime,
      const facebook::jsi::PropNameID &name) override {
    if (name.utf8(runtime) != "locked") {
      return facebook::jsi::Value::undefined();
    }
    const auto locked = lock_and_verify(runtime);
    __android_log_print(
        locked ? ANDROID_LOG_INFO : ANDROID_LOG_ERROR, kLogTag,
        "phase0 weak object JS-thread lock %s",
        locked ? "passed" : "failed");
    return facebook::jsi::Value(locked);
  }

 private:
  bool lock_and_verify(facebook::jsi::Runtime &runtime) const {
    if (!weak_) return false;
    auto value = weak_->lock(runtime);
    if (!value.isObject()) return false;
    auto token = value.asObject(runtime).getProperty(runtime, "token");
    return token.isNumber() && token.asNumber() == 42.0;
  }

  std::optional<facebook::jsi::WeakObject> weak_;
};

void install_weak_object_probe(facebook::jsi::Runtime &runtime) {
  facebook::jsi::Object target(runtime);
  target.setProperty(runtime, "token", 42.0);
  auto probe = facebook::jsi::Object::createFromHostObject(
      runtime, std::make_shared<WeakObjectProbeHost>(runtime, target));
  runtime.global().setProperty(runtime, kWeakProbeGlobal, std::move(probe));
  runtime.global().setProperty(
      runtime, kWeakProbeTargetGlobal, std::move(target));
}
#endif

class AttachedEnv {
 public:
  explicit AttachedEnv(JavaVM *vm) : vm_(vm) {
    if (vm_ == nullptr) return;
    const auto status = vm_->GetEnv(
        reinterpret_cast<void **>(&env_), JNI_VERSION_1_6);
    if (status == JNI_EDETACHED) {
      if (vm_->AttachCurrentThread(&env_, nullptr) == JNI_OK) attached_ = true;
    }
  }
  ~AttachedEnv() {
    if (attached_) vm_->DetachCurrentThread();
  }
  JNIEnv *get() const noexcept { return env_; }

 private:
  JavaVM *vm_{nullptr};
  JNIEnv *env_{nullptr};
  bool attached_{false};
};

void clear_exception(JNIEnv *env, const char *operation) {
  if (env == nullptr || !env->ExceptionCheck()) return;
  __android_log_print(
      ANDROID_LOG_ERROR, kLogTag, "%s raised a Java exception", operation);
  env->ExceptionDescribe();
  env->ExceptionClear();
}

bool publish_runtime_registrar(JNIEnv *env) {
  auto system_class = env->FindClass("java/lang/System");
  auto get_property = system_class == nullptr
      ? nullptr
      : env->GetStaticMethodID(
            system_class, "getProperty",
            "(Ljava/lang/String;)Ljava/lang/String;");
  auto set_property = system_class == nullptr
      ? nullptr
      : env->GetStaticMethodID(
            system_class, "setProperty",
            "(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;");
  auto request_key = env->NewStringUTF(kLoadRequestProperty);
  auto request = get_property == nullptr || request_key == nullptr
      ? nullptr
      : static_cast<jstring>(env->CallStaticObjectMethod(
            system_class, get_property, request_key));
  if (env->ExceptionCheck() || request == nullptr) {
    clear_exception(env, "read runtime generation request");
    return false;
  }
  const char *request_chars = env->GetStringUTFChars(request, nullptr);
  if (request_chars == nullptr) {
    clear_exception(env, "copy runtime generation request");
    return false;
  }
  g_generation_identity.assign(request_chars);
  env->ReleaseStringUTFChars(request, request_chars);
  if (g_generation_identity.empty()) return false;

  const auto publication = g_generation_identity + ":" + std::to_string(
      reinterpret_cast<std::uintptr_t>(&sn_supernote_runtime_b1ee3d0df6ed_register_natives));
  auto key = env->NewStringUTF(kRegistrarProperty);
  auto value = env->NewStringUTF(publication.c_str());
  if (set_property == nullptr || key == nullptr || value == nullptr) {
    clear_exception(env, "prepare runtime registrar publication");
    return false;
  }
  env->CallStaticObjectMethod(system_class, set_property, key, value);
  if (env->ExceptionCheck()) {
    clear_exception(env, "publish runtime registrar");
    return false;
  }
  return true;
}

std::string utf8_bytes(JNIEnv *env, jbyteArray value) {
  if (env == nullptr || value == nullptr) return {};
  const auto length = env->GetArrayLength(value);
  if (env->ExceptionCheck() || length < 0) {
    clear_exception(env, "read coroutine failure");
    return "Kotlin coroutine implementation failed";
  }
  std::string result(static_cast<std::size_t>(length), char{});
  if (length != 0) {
    env->GetByteArrayRegion(
        value, 0, length, reinterpret_cast<jbyte *>(result.data()));
    if (env->ExceptionCheck()) {
      clear_exception(env, "copy coroutine failure");
      return "Kotlin coroutine implementation failed";
    }
  }
  return result;
}

void native_coroutine_complete(
    JNIEnv *env, jclass, jlong completion_id, jobject result,
    jbyteArray failure, jboolean cancelled) {
  supernote::runtime::process_services().complete_jvm_async(
      static_cast<supernote::runtime::SessionId>(completion_id), env, result,
      cancelled == JNI_TRUE
          ? "CANCELLED"
          : (failure == nullptr ? "" : "IMPLEMENTATION_ERROR"),
      utf8_bytes(env, failure));
}

void register_coroutine_bridge(JNIEnv *env, jobject class_loader) {
  auto loader_class = env->GetObjectClass(class_loader);
  auto load_class = loader_class == nullptr
      ? nullptr
      : env->GetMethodID(
            loader_class, "loadClass", "(Ljava/lang/String;)Ljava/lang/Class;");
  auto name = env->NewStringUTF(
      "supernote.generated.runtime.SupernoteCoroutineBridge");
  auto bridge = load_class == nullptr || name == nullptr
      ? nullptr
      : env->CallObjectMethod(class_loader, load_class, name);
  if (env->ExceptionCheck() || bridge == nullptr) {
    clear_exception(env, "load coroutine bridge");
    throw std::runtime_error("generated coroutine bridge is unavailable");
  }
  JNINativeMethod methods[] = {
      {const_cast<char *>("nativeComplete"),
        const_cast<char *>("(JLjava/lang/Object;[BZ)V"),
        reinterpret_cast<void *>(&native_coroutine_complete)},
  };
  if (env->RegisterNatives(
          static_cast<jclass>(bridge), methods,
          static_cast<jint>(sizeof(methods) / sizeof(methods[0]))) != JNI_OK) {
    clear_exception(env, "register coroutine bridge");
    throw std::runtime_error("cannot register coroutine bridge natives");
  }
}

std::shared_ptr<void> global_ref(JNIEnv *env, jobject value) {
  if (env == nullptr || value == nullptr) return {};
  auto *global = env->NewGlobalRef(value);
  if (global == nullptr) throw std::runtime_error("cannot retain JVM object");
  JavaVM *vm = nullptr;
  if (env->GetJavaVM(&vm) != JNI_OK || vm == nullptr) {
    env->DeleteGlobalRef(global);
    throw std::runtime_error("cannot resolve JavaVM");
  }
  auto cleanup = supernote::runtime::process_services().cleanup();
  return std::shared_ptr<void>(global, [vm, cleanup](void *raw) {
    auto release = [vm, raw] {
      AttachedEnv attached(vm);
      if (auto *release_env = attached.get()) {
        release_env->DeleteGlobalRef(static_cast<jobject>(raw));
      }
    };
    if (!cleanup || !cleanup->submit(release)) release();
  });
}

}  // namespace

extern "C" JNIEXPORT jlong JNICALL
Java_supernote_generated_runtime_SupernoteModule_nativeInstall(
    JNIEnv *env, jobject module, jlong runtime_pointer, jobject class_loader,
    jobject platform_context, jobject call_invoker_holder) {
  if (env == nullptr || module == nullptr || class_loader == nullptr ||
      platform_context == nullptr || call_invoker_holder == nullptr ||
      runtime_pointer == 0) {
    return 0;
  }
  try {
    JavaVM *vm = nullptr;
    if (env->GetJavaVM(&vm) != JNI_OK || vm == nullptr) return 0;
    supernote::runtime::process_services().set_java_vm(vm);
    supernote::runtime::process_services().configure_worker_threads([vm] {
      JNIEnv *worker_env = nullptr;
      bool attached = false;
      const auto status = vm->GetEnv(
          reinterpret_cast<void **>(&worker_env), JNI_VERSION_1_6);
      if (status == JNI_EDETACHED) {
        if (vm->AttachCurrentThread(&worker_env, nullptr) != JNI_OK) {
          throw std::runtime_error("cannot attach Supernote worker to JavaVM");
        }
        attached = true;
      } else if (status != JNI_OK) {
        throw std::runtime_error("cannot inspect Supernote worker JVM state");
      }
      return [vm, attached] {
        if (attached) vm->DetachCurrentThread();
      };
    });
    register_coroutine_bridge(env, class_loader);
    auto loader_ref = global_ref(env, class_loader);
    auto context_ref = global_ref(env, platform_context);
    auto holder = facebook::jni::wrap_alias(
        reinterpret_cast<facebook::react::CallInvokerHolder::javaobject>(
            call_invoker_holder));
    auto call_invoker = holder->cthis()->getCallInvoker();
    if (!call_invoker) {
      throw std::runtime_error("React Native JS CallInvoker is unavailable");
    }
    auto scheduler = [call_invoker](
                         supernote::runtime::RuntimeSession::JsTask task) {
      call_invoker->invokeAsync(
          [task = std::move(task)](
              facebook::jsi::Runtime &runtime) mutable {
            task(static_cast<void *>(&runtime));
          });
    };
    auto session = supernote::runtime::RuntimeSession::create(
        std::move(scheduler), std::move(loader_ref), std::move(context_ref));
    auto *runtime = reinterpret_cast<facebook::jsi::Runtime *>(
        static_cast<std::uintptr_t>(runtime_pointer));
    supernote::generated::install_plugin_bindings(*runtime, session);
#if defined(SUPERNOTE_MODULE_WEAK_OBJECT_PROBE)
    install_weak_object_probe(*runtime);
#endif
    const auto session_id = session->id();
    {
      std::lock_guard lock(g_mutex);
      g_sessions.emplace(session_id, std::move(session));
    }
    __android_log_print(
        ANDROID_LOG_INFO, kLogTag, "installed runtime session %llu",
        static_cast<unsigned long long>(session_id));
    return static_cast<jlong>(session_id);
  } catch (const std::exception &error) {
    __android_log_print(
        ANDROID_LOG_ERROR, kLogTag, "runtime installation failed: %s",
        error.what());
    return 0;
  } catch (...) {
    __android_log_print(
        ANDROID_LOG_ERROR, kLogTag, "runtime installation failed");
    return 0;
  }
}

extern "C" JNIEXPORT void JNICALL
Java_supernote_generated_runtime_SupernoteModule_nativeInvalidate(
    JNIEnv *, jobject, jlong session_id) {
  std::shared_ptr<supernote::runtime::RuntimeSession> session;
  {
    std::lock_guard lock(g_mutex);
    auto found = g_sessions.find(static_cast<std::uint64_t>(session_id));
    if (found == g_sessions.end()) return;
    session = found->second;
  }
  __android_log_print(
      ANDROID_LOG_INFO, kLogTag, "invalidating runtime session %llu",
      static_cast<unsigned long long>(session_id));
  const bool retained = session->invalidate();
  if (retained) {
    std::lock_guard lock(g_mutex);
    auto found = g_sessions.find(static_cast<std::uint64_t>(session_id));
    if (found != g_sessions.end() && found->second == session) {
      g_sessions.erase(found);
    }
  } else {
    __android_log_print(
        ANDROID_LOG_ERROR, kLogTag,
        "SNMG_RESTART_REQUIRED: runtime retirement could not be guaranteed "
        "(retained=%zu limit=32); restart PluginHost",
        supernote::runtime::process_services().retired_runtime_count());
  }
  __android_log_print(
      ANDROID_LOG_INFO, kLogTag,
      "logical invalidation completed; physical cleanup remains process-owned");
}

extern "C" __attribute__((visibility("hidden"))) jboolean
sn_supernote_runtime_b1ee3d0df6ed_register_natives(
    JNIEnv *env, jobject class_loader, jstring generation_identity) {
  if (env == nullptr || class_loader == nullptr ||
      generation_identity == nullptr) return JNI_FALSE;
  const char *identity_chars =
      env->GetStringUTFChars(generation_identity, nullptr);
  if (identity_chars == nullptr) {
    clear_exception(env, "read requested runtime generation identity");
    return JNI_FALSE;
  }
  const bool generation_matches = g_generation_identity == identity_chars;
  env->ReleaseStringUTFChars(generation_identity, identity_chars);
  if (!generation_matches) {
    __android_log_print(
        ANDROID_LOG_ERROR, kLogTag,
        "generated runtime generation identity mismatch");
    return JNI_FALSE;
  }
  auto loader_class = env->GetObjectClass(class_loader);
  auto load_class = loader_class == nullptr
      ? nullptr
      : env->GetMethodID(
            loader_class, "loadClass",
            "(Ljava/lang/String;)Ljava/lang/Class;");
  auto module_name = env->NewStringUTF(
      "supernote.generated.runtime.SupernoteModule");
  auto module_class = load_class == nullptr || module_name == nullptr
      ? nullptr
      : env->CallObjectMethod(class_loader, load_class, module_name);
  if (env->ExceptionCheck() || module_class == nullptr) {
    clear_exception(env, "load generated runtime module");
    return JNI_FALSE;
  }
  JNINativeMethod methods[] = {
      {const_cast<char *>("nativeInstall"),
        const_cast<char *>(
            "(JLjava/lang/ClassLoader;"
            "Lcom/facebook/react/bridge/ReactApplicationContext;"
            "Lcom/facebook/react/turbomodule/core/interfaces/"
            "CallInvokerHolder;)J"),
        reinterpret_cast<void *>(
            &Java_supernote_generated_runtime_SupernoteModule_nativeInstall)},
      {const_cast<char *>("nativeInvalidate"),
        const_cast<char *>("(J)V"),
        reinterpret_cast<void *>(
            &Java_supernote_generated_runtime_SupernoteModule_nativeInvalidate)},
  };
  if (env->RegisterNatives(
          static_cast<jclass>(module_class), methods,
          static_cast<jint>(sizeof(methods) / sizeof(methods[0]))) != JNI_OK) {
    clear_exception(env, "register generated runtime natives");
    return JNI_FALSE;
  }
  __android_log_print(
      ANDROID_LOG_INFO, kLogTag,
      "registered runtime natives for plugin ClassLoader %p", class_loader);
  return JNI_TRUE;
}

extern "C" JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM *java_vm, void *) {
  JNIEnv *env = nullptr;
  if (java_vm == nullptr ||
      java_vm->GetEnv(
          reinterpret_cast<void **>(&env), JNI_VERSION_1_6) != JNI_OK ||
      env == nullptr) {
    return JNI_ERR;
  }
  supernote::runtime::process_services().set_java_vm(java_vm);
  return publish_runtime_registrar(env) ? JNI_VERSION_1_6 : JNI_ERR;
}
