// Generated by supernote_module_generator. Do not edit.
#include <jni.h>

#include <android/log.h>
#include <dlfcn.h>
#include <stdint.h>

typedef jboolean (*SupernoteRuntimeRegistrar)(JNIEnv *, jobject, jstring);

JNIEXPORT jboolean JNICALL
Java_supernote_generated_runtime_SupernoteModuleNativeRegistrationBridge_nativeRegister(
    JNIEnv *env,
    jobject bridge,
    jlong registrar_address,
    jstring generation_identity,
    jobject class_loader) {
  if (env == NULL || bridge == NULL || registrar_address == 0 ||
      generation_identity == NULL || class_loader == NULL) {
    return JNI_FALSE;
  }
  SupernoteRuntimeRegistrar registrar =
      (SupernoteRuntimeRegistrar)(uintptr_t)registrar_address;
  Dl_info registrar_info;
  if (dladdr((void *)registrar, &registrar_info) == 0 ||
      registrar_info.dli_fbase == NULL) {
    __android_log_print(
        ANDROID_LOG_ERROR, "SupernoteModuleRegistration",
        "published runtime registrar is no longer mapped");
    return JNI_FALSE;
  }
  const jboolean registered =
      registrar(env, class_loader, generation_identity);
  if (registered != JNI_TRUE) {
    __android_log_print(
        ANDROID_LOG_ERROR, "SupernoteModuleRegistration",
        "current runtime registrar rejected the plugin ClassLoader");
  }
  return registered;
}
