// Generated by supernote_module_generator. Do not edit.
#include "runtime_services.hpp"

#include <algorithm>
#include <chrono>
#include <deque>
#include <stdexcept>
#include <thread>
#include <utility>
#include <vector>

namespace supernote::runtime {
namespace {

std::atomic<SessionId> next_session_id{1};

SessionId allocate_session_id() noexcept {
  return next_session_id.fetch_add(1, std::memory_order_relaxed);
}

}  // namespace

CancellationToken::CancellationToken(
    std::shared_ptr<std::atomic<bool>> state) : state_(std::move(state)) {}

bool CancellationToken::is_cancelled() const noexcept {
  return state_ && state_->load(std::memory_order_acquire);
}

CancellationSource::CancellationSource()
    : state_(std::make_shared<std::atomic<bool>>(false)) {}

CancellationToken CancellationSource::token() const noexcept {
  return CancellationToken(state_);
}

bool CancellationSource::request_cancel() const noexcept {
  return state_ && !state_->exchange(true, std::memory_order_acq_rel);
}

struct BoundedExecutor::WorkHandle::Control {
  std::uint64_t id = 0;
  CancellationSource cancellation;
  std::function<bool(std::uint64_t)> cancel_queued;
  bool accepted = false;
};

struct BoundedExecutor::State {
  struct Item {
    std::uint64_t id;
    CancellationSource cancellation;
    Task task;
  };

  State(std::size_t worker_count, std::size_t capacity)
      : worker_count(worker_count), capacity(capacity) {}
  std::mutex mutex;
  std::condition_variable ready;
  std::deque<Item> queue;
  std::vector<std::thread> workers;
  std::size_t worker_count;
  std::size_t capacity;
  std::atomic<std::size_t> live_workers{0};
  std::uint64_t next_id = 1;
  ThreadInitializer thread_initializer;
  bool stopped = false;
};

BoundedExecutor::WorkHandle::WorkHandle(std::shared_ptr<Control> control)
    : control_(std::move(control)) {}

bool BoundedExecutor::WorkHandle::accepted() const noexcept {
  return control_ && control_->accepted;
}

bool BoundedExecutor::WorkHandle::cancel() const noexcept {
  if (!control_) return false;
  control_->cancellation.request_cancel();
  return control_->cancel_queued && control_->cancel_queued(control_->id);
}

CancellationToken BoundedExecutor::WorkHandle::token() const noexcept {
  return control_ ? control_->cancellation.token() : CancellationToken{};
}

BoundedExecutor::BoundedExecutor(std::size_t worker_count,
                                 std::size_t queue_capacity)
    : state_(std::make_shared<State>(worker_count, queue_capacity)) {
  if (worker_count == 0 || queue_capacity == 0) {
    throw std::invalid_argument("executor size and capacity must be positive");
  }
}

void BoundedExecutor::ensure_started() {
  auto state = state_;
  std::lock_guard lock(state->mutex);
  if (state->stopped) {
    throw std::runtime_error("executor is stopped");
  }
  if (!state->workers.empty()) return;
  state->workers.reserve(state->worker_count);
  for (std::size_t index = 0; index < state->worker_count; ++index) {
    state_->workers.emplace_back([state = state_] {
      state->live_workers.fetch_add(1, std::memory_order_acq_rel);
      bool thread_initialized = false;
      std::function<void()> thread_cleanup;
      while (true) {
        State::Item item;
        {
          std::unique_lock lock(state->mutex);
          state->ready.wait(lock, [&] {
            return state->stopped || !state->queue.empty();
          });
          if (state->queue.empty()) {
            if (state->stopped) break;
            continue;
          }
          item = std::move(state->queue.front());
          state->queue.pop_front();
        }
        if (!thread_initialized) {
          ThreadInitializer initializer;
          {
            std::lock_guard lock(state->mutex);
            initializer = state->thread_initializer;
          }
          if (initializer) {
            try {
              thread_cleanup = initializer();
              thread_initialized = true;
            } catch (...) {
              // A later task may retry initialization. The current task still
              // owns its normal error/completion path.
            }
          }
        }
        if (item.cancellation.token().is_cancelled()) continue;
        try {
          item.task(item.cancellation.token());
        } catch (...) {
          // Generated completion paths translate failures. An escaping task
          // must never terminate the shared executor.
        }
      }
      if (thread_cleanup) {
        try { thread_cleanup(); } catch (...) {}
      }
      state->live_workers.fetch_sub(1, std::memory_order_acq_rel);
    });
  }
}

BoundedExecutor::~BoundedExecutor() { shutdown(); }

BoundedExecutor::WorkHandle BoundedExecutor::submit(Task task) {
  if (!task) return {};
  ensure_started();
  auto control = std::make_shared<WorkHandle::Control>();
  auto state = state_;
  {
    std::lock_guard lock(state->mutex);
    if (state->stopped || state->queue.size() >= state->capacity) {
      return WorkHandle(control);
    }
    control->id = state->next_id++;
    control->accepted = true;
    state->queue.push_back(
        {control->id, control->cancellation, std::move(task)});
  }
  control->cancel_queued = [weak = std::weak_ptr<State>(state)](
                               std::uint64_t id) {
    auto locked = weak.lock();
    if (!locked) return false;
    std::lock_guard guard(locked->mutex);
    auto found = std::find_if(
        locked->queue.begin(), locked->queue.end(),
        [id](const State::Item &item) { return item.id == id; });
    if (found == locked->queue.end()) return false;
    locked->queue.erase(found);
    return true;
  };
  state->ready.notify_one();
  return WorkHandle(std::move(control));
}

void BoundedExecutor::set_thread_initializer(
    ThreadInitializer initializer) {
  if (!initializer) {
    throw std::invalid_argument("worker thread initializer is required");
  }
  auto state = state_;
  std::lock_guard lock(state->mutex);
  if (state->stopped) {
    throw std::runtime_error("executor is stopped");
  }
  state->thread_initializer = std::move(initializer);
}

std::size_t BoundedExecutor::thread_count() const noexcept {
  auto state = state_;
  return state
      ? state->live_workers.load(std::memory_order_acquire)
      : 0;
}

void BoundedExecutor::shutdown() noexcept {
  auto state = state_;
  if (!state) return;
  {
    std::lock_guard lock(state->mutex);
    if (state->stopped) return;
    state->stopped = true;
    for (auto &item : state->queue) item.cancellation.request_cancel();
    state->queue.clear();
  }
  state->ready.notify_all();
  for (auto &worker : state->workers) {
    if (worker.joinable()) worker.join();
  }
  state->workers.clear();
}

struct DeferredDestruction::State {
  struct Item {
    std::chrono::steady_clock::time_point enqueued;
    std::function<void()> cleanup;
  };

  explicit State(std::size_t requested_capacity) : capacity(requested_capacity) {}
  std::mutex mutex;
  std::condition_variable ready;
  std::deque<Item> queue;
  std::thread worker;
  std::atomic<std::size_t> live_workers{0};
  const std::size_t capacity;
  std::atomic<std::size_t> high_water{0};
  std::atomic<std::uint64_t> processed{0};
  std::atomic<std::uint64_t> failures{0};
  bool stopping = false;
};

DeferredDestruction::DeferredDestruction(std::size_t queue_capacity)
    : state_(std::make_shared<State>(queue_capacity)) {
  if (queue_capacity == 0) {
    throw std::invalid_argument("deferred destruction capacity must be positive");
  }
}

DeferredDestruction::~DeferredDestruction() { drain_and_shutdown(); }

bool DeferredDestruction::submit(std::function<void()> cleanup) noexcept {
  if (!cleanup) return true;
  auto state = state_;
  try {
    {
      std::lock_guard lock(state->mutex);
      if (state->stopping) return false;
      if (state->queue.size() >= state->capacity) return false;
      if (!state->worker.joinable()) {
        state->worker = std::thread([state] {
          state->live_workers.fetch_add(1, std::memory_order_acq_rel);
          while (true) {
            State::Item item;
            {
              std::unique_lock worker_lock(state->mutex);
              state->ready.wait(worker_lock, [&] {
                return state->stopping || !state->queue.empty();
              });
              if (state->queue.empty() && state->stopping) break;
              item = std::move(state->queue.front());
              state->queue.pop_front();
            }
            try {
              item.cleanup();
              state->processed.fetch_add(1, std::memory_order_acq_rel);
            } catch (...) {
              state->failures.fetch_add(1, std::memory_order_acq_rel);
              // Cleanup never crosses into JSI and never stops the facility.
            }
          }
          state->live_workers.fetch_sub(1, std::memory_order_acq_rel);
        });
      }
      state->queue.push_back(
          {std::chrono::steady_clock::now(), std::move(cleanup)});
      const auto depth = state->queue.size();
      auto previous = state->high_water.load(std::memory_order_acquire);
      while (depth > previous &&
             !state->high_water.compare_exchange_weak(
                 previous, depth, std::memory_order_acq_rel)) {}
    }
    state->ready.notify_one();
    return true;
  } catch (...) {
    return false;
  }
}

std::size_t DeferredDestruction::thread_count() const noexcept {
  auto state = state_;
  return state
      ? state->live_workers.load(std::memory_order_acquire)
      : 0;
}

std::size_t DeferredDestruction::queue_depth() const noexcept {
  auto state = state_;
  if (!state) return 0;
  std::lock_guard lock(state->mutex);
  return state->queue.size();
}

std::size_t DeferredDestruction::high_water_mark() const noexcept {
  return state_ ? state_->high_water.load(std::memory_order_acquire) : 0;
}

std::uint64_t DeferredDestruction::oldest_item_age_ms() const noexcept {
  auto state = state_;
  if (!state) return 0;
  std::lock_guard lock(state->mutex);
  if (state->queue.empty()) return 0;
  return static_cast<std::uint64_t>(
      std::chrono::duration_cast<std::chrono::milliseconds>(
          std::chrono::steady_clock::now() - state->queue.front().enqueued)
          .count());
}

std::uint64_t DeferredDestruction::processed_count() const noexcept {
  return state_ ? state_->processed.load(std::memory_order_acquire) : 0;
}

std::uint64_t DeferredDestruction::failure_count() const noexcept {
  return state_ ? state_->failures.load(std::memory_order_acquire) : 0;
}

void DeferredDestruction::drain_and_shutdown() noexcept {
  auto state = state_;
  if (!state) return;
  {
    std::lock_guard lock(state->mutex);
    state->stopping = true;
  }
  state->ready.notify_all();
  if (state->worker.joinable()) state->worker.join();
}

RuntimeSession::RuntimeSession(SessionId id, JsScheduler scheduler,
                               std::shared_ptr<void> plugin_class_loader,
                               std::shared_ptr<void> platform_context)
    : id_(id),
      scheduler_(std::move(scheduler)),
      plugin_class_loader_(std::move(plugin_class_loader)),
      platform_context_(std::move(platform_context)) {}

std::shared_ptr<RuntimeSession> RuntimeSession::create(
    JsScheduler scheduler, std::shared_ptr<void> plugin_class_loader,
    std::shared_ptr<void> platform_context) {
  if (!scheduler) throw std::invalid_argument("JS scheduler is required");
  // Construct bounded process-lifetime infrastructure before user work can
  // inject allocation failures into invalidation.
  (void)process_services();
  return std::shared_ptr<RuntimeSession>(new RuntimeSession(
      allocate_session_id(), std::move(scheduler),
      std::move(plugin_class_loader), std::move(platform_context)));
}

SessionId RuntimeSession::id() const noexcept { return id_; }

bool RuntimeSession::active() const noexcept {
  return active_.load(std::memory_order_acquire);
}

bool RuntimeSession::schedule(JsTask task) noexcept {
  if (!task || !active()) return false;
  auto weak = weak_from_this();
  const auto expected = id_;
  JsScheduler scheduler;
  {
    std::lock_guard lock(mutex_);
    if (!active() || !scheduler_) return false;
    scheduler = scheduler_;
  }
  try {
    scheduler([weak, expected, task = std::move(task)](void *runtime) mutable {
      auto session = weak.lock();
      if (!session || session->id_ != expected || !session->active() ||
          runtime == nullptr) {
        return;
      }
      task(runtime);
    });
    return true;
  } catch (...) {
    return false;
  }
}

void RuntimeSession::add_feature(
    const std::shared_ptr<FeatureSession> &feature) {
  std::lock_guard lock(mutex_);
  if (!active()) throw std::runtime_error(
      "SNMG_SESSION_INVALIDATED: runtime session is inactive");
  features_[feature->id()] = feature;
}

void RuntimeSession::remove_feature(SessionId feature_id) noexcept {
  std::lock_guard lock(mutex_);
  features_.erase(feature_id);
}

bool RuntimeSession::invalidate() noexcept {
  active_.store(false, std::memory_order_release);
  try {
    return process_services().retire_runtime(shared_from_this());
  } catch (...) {
    return false;
  }
}

void RuntimeSession::cleanup_physical() noexcept {
  {
    std::lock_guard lock(mutex_);
    plugin_class_loader_.reset();
    platform_context_.reset();
    scheduler_ = {};
  }
  for (;;) {
    std::shared_ptr<FeatureSession> feature;
    {
      std::lock_guard lock(mutex_);
      if (features_.empty()) break;
      auto current = features_.begin();
      feature = std::move(current->second);
      features_.erase(current);
    }
    feature->close_runtime();
  }
}

std::shared_ptr<void> RuntimeSession::plugin_class_loader() const noexcept {
  std::lock_guard lock(mutex_);
  return plugin_class_loader_;
}

std::shared_ptr<void> RuntimeSession::platform_context() const noexcept {
  std::lock_guard lock(mutex_);
  return platform_context_;
}

PendingOperation::PendingOperation(
    SessionId id, TeardownRejection rejection,
    std::shared_ptr<void> internal_completion)
    : id_(id),
      internal_completion_(std::move(internal_completion)),
      rejection_(std::move(rejection)) {}

SessionId PendingOperation::id() const noexcept { return id_; }

OperationWinner PendingOperation::winner() const noexcept {
  return winner_.load(std::memory_order_acquire);
}

CancellationToken PendingOperation::cancellation_token() const noexcept {
  return cancellation_.token();
}

void PendingOperation::set_work(BoundedExecutor::WorkHandle work) noexcept {
  std::lock_guard lock(mutex_);
  work_ = std::move(work);
  if (winner() != OperationWinner::PENDING) work_.cancel();
}

void PendingOperation::set_cancel_hook(std::function<void()> hook) noexcept {
  if (!hook) return;
  bool run_now = false;
  {
    std::lock_guard lock(mutex_);
    const auto current = winner();
    if (current == OperationWinner::PENDING) {
      cancel_hook_ = std::move(hook);
      return;
    }
    run_now = current == OperationWinner::CANCELLED_BY_FEATURE ||
        current == OperationWinner::CANCELLED_BY_RUNTIME;
  }
  if (run_now) {
    try { hook(); } catch (...) {}
  }
}

void PendingOperation::set_retained_state(std::shared_ptr<void> state) noexcept {
  std::lock_guard lock(mutex_);
  retained_state_ = std::move(state);
}

std::shared_ptr<void> PendingOperation::take_internal_completion() noexcept {
  std::lock_guard lock(mutex_);
  return std::move(internal_completion_);
}

bool PendingOperation::claim(OperationWinner winner) noexcept {
  auto expected = OperationWinner::PENDING;
  if (!winner_.compare_exchange_strong(expected, winner,
                                       std::memory_order_acq_rel)) {
    return false;
  }
  if (winner == OperationWinner::CANCELLED_BY_FEATURE ||
      winner == OperationWinner::CANCELLED_BY_RUNTIME) {
    cancellation_.request_cancel();
    std::function<void()> hook;
    {
      std::lock_guard lock(mutex_);
      work_.cancel();
      hook = std::move(cancel_hook_);
    }
    if (hook) {
      try { hook(); } catch (...) {}
    }
  } else if (winner == OperationWinner::COMPLETING) {
    std::lock_guard lock(mutex_);
    cancel_hook_ = {};
  }
  return true;
}

PendingOperation::TeardownRejection PendingOperation::take_rejection() noexcept {
  std::lock_guard lock(mutex_);
  return std::move(rejection_);
}

FeatureSession::FeatureSession(SessionId id,
                               std::shared_ptr<RuntimeSession> runtime,
                               std::shared_ptr<DeferredDestruction> cleanup)
    : id_(id), runtime_(std::move(runtime)), cleanup_(std::move(cleanup)) {}

std::shared_ptr<FeatureSession> FeatureSession::create(
    const std::shared_ptr<RuntimeSession> &runtime,
    std::shared_ptr<DeferredDestruction> cleanup) {
  if (!runtime || !runtime->active()) {
    throw std::invalid_argument("active runtime session is required");
  }
  if (!cleanup) throw std::invalid_argument("cleanup facility is required");
  auto feature = std::shared_ptr<FeatureSession>(new FeatureSession(
      allocate_session_id(), runtime, std::move(cleanup)));
  runtime->add_feature(feature);
  return feature;
}

SessionId FeatureSession::id() const noexcept { return id_; }

FeatureState FeatureSession::state() const noexcept {
  return state_.load(std::memory_order_acquire);
}

std::shared_ptr<RuntimeSession> FeatureSession::runtime() const noexcept {
  std::lock_guard lock(mutex_);
  return runtime_.lock();
}

std::shared_ptr<PendingOperation> FeatureSession::accept(
    PendingOperation::TeardownRejection rejection,
    std::shared_ptr<void> internal_completion) {
  std::lock_guard lock(mutex_);
  auto runtime = runtime_.lock();
  if (state() != FeatureState::ACTIVE || !runtime || !runtime->active()) {
    return {};
  }
  auto operation = std::shared_ptr<PendingOperation>(
      new PendingOperation(
          allocate_session_id(), std::move(rejection),
          std::move(internal_completion)));
  pending_.emplace(operation->id(), operation);
  return operation;
}

std::shared_ptr<PendingOperation> FeatureSession::accept_factory(
    std::function<PendingOperation::TeardownRejection(SessionId)> factory) {
  std::lock_guard lock(mutex_);
  auto runtime = runtime_.lock();
  if (!factory || state() != FeatureState::ACTIVE || !runtime ||
      !runtime->active()) {
    return {};
  }
  const auto id = allocate_session_id();
  auto operation = std::shared_ptr<PendingOperation>(
      new PendingOperation(id, factory(id)));
  pending_.emplace(operation->id(), operation);
  return operation;
}

bool FeatureSession::schedule_completion(
    const std::shared_ptr<PendingOperation> &operation,
    RuntimeSession::JsTask completion) noexcept {
  if (!operation || !completion) return false;
  std::shared_ptr<RuntimeSession> runtime;
  {
    std::lock_guard lock(mutex_);
    if (state() != FeatureState::ACTIVE) return false;
    runtime = runtime_.lock();
    if (!runtime || !runtime->active()) return false;
  }
  auto weak = weak_from_this();
  const auto expected_feature = id_;
  return runtime->schedule(
      [weak, expected_feature, operation,
       completion = std::move(completion)](void *js_runtime) mutable {
        auto feature = weak.lock();
        if (!feature || feature->id_ != expected_feature) return;
        {
          std::lock_guard lock(feature->mutex_);
          if (feature->state() != FeatureState::ACTIVE ||
              !operation->claim(OperationWinner::COMPLETING)) {
            return;
          }
          feature->pending_.erase(operation->id());
        }
        operation->take_rejection();
        completion(js_runtime);
      });
}

bool FeatureSession::claim_internal_completion(
    const std::shared_ptr<PendingOperation> &operation) noexcept {
  if (!operation) return false;
  std::lock_guard lock(mutex_);
  if (state() != FeatureState::ACTIVE ||
      !operation->claim(OperationWinner::COMPLETING)) {
    return false;
  }
  pending_.erase(operation->id());
  operation->take_rejection();
  return true;
}

void FeatureSession::close_feature() noexcept { close(false); }

void FeatureSession::close_runtime() noexcept { close(true); }

void FeatureSession::close(bool runtime_teardown) noexcept {
  std::shared_ptr<RuntimeSession> runtime;
  {
    std::lock_guard lock(mutex_);
    if (state() != FeatureState::ACTIVE) return;
    state_.store(FeatureState::CLOSING, std::memory_order_release);
    runtime = runtime_.lock();
  }

  if (!runtime_teardown && runtime) runtime->remove_feature(id_);
  for (;;) {
    std::shared_ptr<PendingOperation> operation;
    {
      std::lock_guard lock(mutex_);
      if (pending_.empty()) break;
      auto current = pending_.begin();
      operation = std::move(current->second);
      pending_.erase(current);
    }
    const auto outcome = runtime_teardown
        ? OperationWinner::CANCELLED_BY_RUNTIME
        : OperationWinner::CANCELLED_BY_FEATURE;
    if (!operation->claim(outcome)) continue;
    auto internal_completion = operation->take_internal_completion();
    if (internal_completion) {
      defer_release(std::move(internal_completion));
    }
    auto rejection = operation->take_rejection();
    if (!runtime_teardown && runtime && runtime->active() && rejection) {
      runtime->schedule(std::move(rejection));
    }
  }
  for (;;) {
    std::shared_ptr<ServiceSlot> slot;
    {
      std::lock_guard lock(mutex_);
      if (services_.empty()) break;
      auto current = services_.begin();
      slot = std::move(current->second);
      services_.erase(current);
    }
    std::shared_ptr<void> service;
    {
      std::lock_guard slot_lock(slot->mutex);
      service = std::move(slot->value);
    }
    defer_release(std::move(service));
  }
  {
    std::lock_guard lock(mutex_);
    runtime_.reset();
    state_.store(FeatureState::INACTIVE, std::memory_order_release);
  }
}

void FeatureSession::erase_pending(SessionId operation_id) noexcept {
  std::lock_guard lock(mutex_);
  pending_.erase(operation_id);
}

namespace {
thread_local std::weak_ptr<FeatureSession> g_current_feature;
}

FeatureCallScope::FeatureCallScope(
    std::shared_ptr<FeatureSession> feature) noexcept
    : previous_(g_current_feature) {
  g_current_feature = feature;
}

FeatureCallScope::~FeatureCallScope() {
  g_current_feature = previous_;
}

std::shared_ptr<FeatureSession> current_feature_session() noexcept {
  return g_current_feature.lock();
}

ProcessServices::ProcessServices()
    : workers_(std::max<std::size_t>(1, std::thread::hardware_concurrency()),
               256),
      cleanup_(std::make_shared<DeferredDestruction>()) {}

ProcessServices::~ProcessServices() { shutdown(); }

BoundedExecutor &ProcessServices::workers() noexcept { return workers_; }

void ProcessServices::configure_worker_threads(
    BoundedExecutor::ThreadInitializer initializer) {
  workers_.set_thread_initializer(std::move(initializer));
}

std::shared_ptr<DeferredDestruction> ProcessServices::cleanup() const noexcept {
  return cleanup_;
}

void ProcessServices::set_java_vm(void *java_vm) noexcept {
  java_vm_.store(java_vm, std::memory_order_release);
}

void *ProcessServices::java_vm() const noexcept {
  return java_vm_.load(std::memory_order_acquire);
}

SessionId ProcessServices::register_jvm_async_completion(
    JvmAsyncCompletion completion) {
  if (!completion) {
    throw std::invalid_argument("JVM async completion is required");
  }
  const auto id = allocate_session_id();
  std::lock_guard lock(jvm_async_mutex_);
  jvm_async_completions_.emplace(id, std::move(completion));
  return id;
}

bool ProcessServices::discard_jvm_async_completion(
    SessionId completion_id) noexcept {
  std::lock_guard lock(jvm_async_mutex_);
  return jvm_async_completions_.erase(completion_id) != 0;
}

void ProcessServices::complete_jvm_async(
    SessionId completion_id,
    void *environment,
    void *result,
    std::string error_code,
    std::string failure) noexcept {
  JvmAsyncCompletion completion;
  {
    std::lock_guard lock(jvm_async_mutex_);
    auto found = jvm_async_completions_.find(completion_id);
    if (found == jvm_async_completions_.end()) return;
    completion = std::move(found->second);
    jvm_async_completions_.erase(found);
  }
  try {
    completion(environment, result, std::move(error_code), std::move(failure));
  } catch (...) {
    // Native-async completion must never unwind through JNI/coroutine code.
  }
}

bool ProcessServices::retire_runtime(
    std::shared_ptr<RuntimeSession> runtime) noexcept {
  if (!runtime) return true;
  try {
    constexpr std::size_t kRetiredRuntimeLimit = 32;
    const auto id = runtime->id();
    {
      std::lock_guard lock(retired_runtime_mutex_);
      if (retired_runtimes_.find(id) == retired_runtimes_.end()) {
        if (retired_runtimes_.size() >= kRetiredRuntimeLimit) {
          restart_required_.store(true, std::memory_order_release);
          return false;
        }
        retired_runtimes_.emplace(id, std::move(runtime));
      }
    }
    if (!try_schedule_retired_runtime(id) &&
        !ensure_retirement_retry_worker()) {
      return false;
    }
    return true;
  } catch (...) {
    restart_required_.store(true, std::memory_order_release);
    return false;
  }
}

bool ProcessServices::try_schedule_retired_runtime(SessionId id) noexcept {
  try {
    {
      std::lock_guard lock(retired_runtime_mutex_);
      if (retired_runtimes_.find(id) == retired_runtimes_.end() ||
          scheduled_retirements_.find(id) != scheduled_retirements_.end()) {
        return true;
      }
      scheduled_retirements_.insert(id);
    }
    const auto accepted = cleanup_ && cleanup_->submit([this, id] {
      std::shared_ptr<RuntimeSession> retired;
      {
        std::lock_guard lock(retired_runtime_mutex_);
        scheduled_retirements_.erase(id);
        auto found = retired_runtimes_.find(id);
        if (found == retired_runtimes_.end()) return;
        retired = std::move(found->second);
        retired_runtimes_.erase(found);
      }
      retired->cleanup_physical();
      retirement_ready_.notify_all();
    });
    if (accepted) return true;
    {
      std::lock_guard lock(retired_runtime_mutex_);
      scheduled_retirements_.erase(id);
    }
    return false;
  } catch (...) {
    std::lock_guard lock(retired_runtime_mutex_);
    scheduled_retirements_.erase(id);
    return false;
  }
}

bool ProcessServices::ensure_retirement_retry_worker() noexcept {
  try {
    {
      std::lock_guard lock(retired_runtime_mutex_);
      if (retirement_stopping_) {
        restart_required_.store(true, std::memory_order_release);
        return false;
      }
      if (!retirement_retry_worker_.joinable()) {
        retirement_retry_worker_ =
            std::thread([this] { retirement_retry_loop(); });
      }
    }
    retirement_ready_.notify_one();
    return true;
  } catch (...) {
    restart_required_.store(true, std::memory_order_release);
    return false;
  }
}

void ProcessServices::retirement_retry_loop() noexcept {
  while (true) {
    SessionId candidate = 0;
    {
      std::unique_lock lock(retired_runtime_mutex_);
      retirement_ready_.wait(lock, [&] {
        if (retirement_stopping_) return true;
        for (const auto &[id, runtime] : retired_runtimes_) {
          (void)runtime;
          if (scheduled_retirements_.find(id) == scheduled_retirements_.end()) {
            return true;
          }
        }
        return false;
      });
      if (retirement_stopping_) return;
      for (const auto &[id, runtime] : retired_runtimes_) {
        (void)runtime;
        if (scheduled_retirements_.find(id) == scheduled_retirements_.end()) {
          candidate = id;
          break;
        }
      }
    }
    if (candidate != 0 && try_schedule_retired_runtime(candidate)) continue;
    std::unique_lock lock(retired_runtime_mutex_);
    retirement_ready_.wait_for(
        lock, std::chrono::milliseconds(10),
        [&] { return retirement_stopping_; });
    if (retirement_stopping_) return;
  }
}

std::size_t ProcessServices::retired_runtime_count() const noexcept {
  std::lock_guard lock(retired_runtime_mutex_);
  return retired_runtimes_.size();
}

bool ProcessServices::restart_required() const noexcept {
  return restart_required_.load(std::memory_order_acquire);
}

std::size_t ProcessServices::thread_count() const noexcept {
  std::lock_guard lock(retired_runtime_mutex_);
  return workers_.thread_count() + cleanup_->thread_count() +
      (retirement_retry_worker_.joinable() ? 1 : 0);
}

void ProcessServices::shutdown() noexcept {
  {
    std::lock_guard lock(retired_runtime_mutex_);
    retirement_stopping_ = true;
  }
  retirement_ready_.notify_all();
  if (retirement_retry_worker_.joinable()) retirement_retry_worker_.join();
  workers_.shutdown();
  {
    std::lock_guard lock(jvm_async_mutex_);
    jvm_async_completions_.clear();
  }
  cleanup_->drain_and_shutdown();
  std::unordered_map<SessionId, std::shared_ptr<RuntimeSession>> retired;
  {
    std::lock_guard lock(retired_runtime_mutex_);
    retired.swap(retired_runtimes_);
    scheduled_retirements_.clear();
  }
  for (auto &[id, runtime] : retired) {
    (void)id;
    runtime->cleanup_physical();
  }
  java_vm_.store(nullptr, std::memory_order_release);
}

ProcessServices &process_services() noexcept {
  static ProcessServices services;
  return services;
}

}  // namespace supernote::runtime
