// Generated by supernote_module_generator. Do not edit.
#pragma once

#include <atomic>
#include <condition_variable>
#include <cstddef>
#include <cstdint>
#include <exception>
#include <functional>
#include <memory>
#include <mutex>
#include <string>
#include <stdexcept>
#include <thread>
#include <type_traits>
#include <unordered_map>
#include <unordered_set>
#include <utility>

namespace supernote::runtime {

using SessionId = std::uint64_t;

class CancellationToken {
 public:
  CancellationToken() = default;
  bool is_cancelled() const noexcept;

 private:
  explicit CancellationToken(std::shared_ptr<std::atomic<bool>> state);
  std::shared_ptr<std::atomic<bool>> state_;
  friend class CancellationSource;
};

class CancellationSource {
 public:
  CancellationSource();
  CancellationToken token() const noexcept;
  bool request_cancel() const noexcept;

 private:
  std::shared_ptr<std::atomic<bool>> state_;
};

class BoundedExecutor {
 public:
  using Task = std::function<void(CancellationToken)>;
  using ThreadInitializer =
      std::function<std::function<void()>()>;

  class WorkHandle {
   public:
    WorkHandle() = default;
    bool accepted() const noexcept;
    bool cancel() const noexcept;
    CancellationToken token() const noexcept;

   private:
    struct Control;
    explicit WorkHandle(std::shared_ptr<Control> control);
    std::shared_ptr<Control> control_;
    friend class BoundedExecutor;
  };

  BoundedExecutor(std::size_t worker_count, std::size_t queue_capacity);
  ~BoundedExecutor();
  BoundedExecutor(const BoundedExecutor &) = delete;
  BoundedExecutor &operator=(const BoundedExecutor &) = delete;

  WorkHandle submit(Task task);
  void set_thread_initializer(ThreadInitializer initializer);
  std::size_t thread_count() const noexcept;
  void shutdown() noexcept;

 private:
  struct State;
  void ensure_started();
  std::shared_ptr<State> state_;
};

class DeferredDestruction {
 public:
  explicit DeferredDestruction(std::size_t queue_capacity = 1024);
  ~DeferredDestruction();
  DeferredDestruction(const DeferredDestruction &) = delete;
  DeferredDestruction &operator=(const DeferredDestruction &) = delete;

  bool submit(std::function<void()> cleanup) noexcept;
  template <typename Cleanup>
  bool submit(Cleanup &&cleanup) noexcept {
    try {
      return submit(std::function<void()>(
          std::forward<Cleanup>(cleanup)));
    } catch (...) {
      return false;
    }
  }
  std::size_t thread_count() const noexcept;
  std::size_t queue_depth() const noexcept;
  std::size_t high_water_mark() const noexcept;
  std::uint64_t oldest_item_age_ms() const noexcept;
  std::uint64_t processed_count() const noexcept;
  std::uint64_t failure_count() const noexcept;
  void drain_and_shutdown() noexcept;

 private:
  struct State;
  std::shared_ptr<State> state_;
};

template <typename T>
class ManagedRef {
 public:
  ManagedRef() = default;
  ManagedRef(std::shared_ptr<T> value,
             std::shared_ptr<DeferredDestruction> cleanup)
      : value_(std::move(value)), cleanup_(std::move(cleanup)) {}
  ManagedRef(const ManagedRef &) = default;
  ManagedRef &operator=(const ManagedRef &other) {
    if (this == &other) return *this;
    reset();
    value_ = other.value_;
    cleanup_ = other.cleanup_;
    return *this;
  }
  ManagedRef(ManagedRef &&) noexcept = default;
  ManagedRef &operator=(ManagedRef && other) noexcept {
    if (this == &other) return *this;
    reset();
    value_ = std::move(other.value_);
    cleanup_ = std::move(other.cleanup_);
    return *this;
  }
  ~ManagedRef() { reset(); }

  T *get() const noexcept { return value_.get(); }
  T &operator*() const noexcept { return *value_; }
  T *operator->() const noexcept { return value_.get(); }
  const std::shared_ptr<T> &shared_ref() const noexcept { return value_; }
  explicit operator bool() const noexcept { return static_cast<bool>(value_); }

  void reset() noexcept {
    auto value = std::move(value_);
    auto cleanup = cleanup_;
    cleanup_.reset();
    if (!value) return;
    if (cleanup && cleanup->submit(
        [value = std::move(value)]() mutable { value.reset(); })) return;
    // Queue admission can fail during component shutdown or memory pressure.
    // Inline release is the bounded fallback and cannot touch JSI.
    value.reset();
  }

 private:
  std::shared_ptr<T> value_;
  std::shared_ptr<DeferredDestruction> cleanup_;
};

class FeatureSession;

class RuntimeSession : public std::enable_shared_from_this<RuntimeSession> {
 public:
  using JsTask = std::function<void(void *runtime)>;
  using JsScheduler = std::function<void(JsTask)>;

  static std::shared_ptr<RuntimeSession> create(
      JsScheduler scheduler,
      std::shared_ptr<void> plugin_class_loader = {},
      std::shared_ptr<void> platform_context = {});

  SessionId id() const noexcept;
  bool active() const noexcept;
  bool schedule(JsTask task) noexcept;
  bool invalidate() noexcept;
  std::shared_ptr<void> plugin_class_loader() const noexcept;
  std::shared_ptr<void> platform_context() const noexcept;

 private:
  RuntimeSession(SessionId id, JsScheduler scheduler,
                 std::shared_ptr<void> plugin_class_loader,
                 std::shared_ptr<void> platform_context);
  void cleanup_physical() noexcept;
  void add_feature(const std::shared_ptr<FeatureSession> &feature);
  void remove_feature(SessionId feature_id) noexcept;

  SessionId id_;
  JsScheduler scheduler_;
  std::shared_ptr<void> plugin_class_loader_;
  std::shared_ptr<void> platform_context_;
  std::atomic<bool> active_{true};
  mutable std::mutex mutex_;
  std::unordered_map<SessionId, std::shared_ptr<FeatureSession>> features_;
  friend class FeatureSession;
  friend class ProcessServices;
};

enum class FeatureState { ACTIVE, CLOSING, INACTIVE };
enum class OperationWinner {
  PENDING,
  COMPLETING,
  CANCELLED_BY_FEATURE,
  CANCELLED_BY_RUNTIME,
};

class PendingOperation {
 public:
  using TeardownRejection = std::function<void(void *runtime)>;

  SessionId id() const noexcept;
  OperationWinner winner() const noexcept;
  CancellationToken cancellation_token() const noexcept;
  void set_work(BoundedExecutor::WorkHandle work) noexcept;
  void set_cancel_hook(std::function<void()> hook) noexcept;
  void set_retained_state(std::shared_ptr<void> state) noexcept;
  std::shared_ptr<void> take_internal_completion() noexcept;

 private:
  PendingOperation(SessionId id, TeardownRejection rejection,
                   std::shared_ptr<void> internal_completion = {});
  bool claim(OperationWinner winner) noexcept;
  TeardownRejection take_rejection() noexcept;

  SessionId id_;
  std::atomic<OperationWinner> winner_{OperationWinner::PENDING};
  CancellationSource cancellation_;
  std::mutex mutex_;
  BoundedExecutor::WorkHandle work_;
  std::function<void()> cancel_hook_;
  std::shared_ptr<void> retained_state_;
  std::shared_ptr<void> internal_completion_;
  TeardownRejection rejection_;
  friend class FeatureSession;
};

class FeatureSession : public std::enable_shared_from_this<FeatureSession> {
 public:
  static std::shared_ptr<FeatureSession> create(
      const std::shared_ptr<RuntimeSession> &runtime,
      std::shared_ptr<DeferredDestruction> cleanup);

  SessionId id() const noexcept;
  FeatureState state() const noexcept;
  std::shared_ptr<RuntimeSession> runtime() const noexcept;
  std::shared_ptr<PendingOperation> accept(
      PendingOperation::TeardownRejection rejection,
      std::shared_ptr<void> internal_completion = {});
  std::shared_ptr<PendingOperation> accept_factory(
      std::function<PendingOperation::TeardownRejection(SessionId)> factory);
  bool schedule_completion(
      const std::shared_ptr<PendingOperation> &operation,
      RuntimeSession::JsTask completion) noexcept;
  bool claim_internal_completion(
      const std::shared_ptr<PendingOperation> &operation) noexcept;
  void close_feature() noexcept;
  void close_runtime() noexcept;

  template <typename T, typename Factory>
  ManagedRef<T> service(const std::string &declaration_id,
                        Factory &&factory) {
    static_assert(std::is_invocable_r_v<std::shared_ptr<T>, Factory>);
    std::shared_ptr<ServiceSlot> slot;
    std::uint64_t attempt = 0;
    {
      std::unique_lock lock(mutex_);
      if (state_.load(std::memory_order_acquire) != FeatureState::ACTIVE) {
        throw std::runtime_error("feature session is closed");
      }
      auto &stored = services_[declaration_id];
      if (!stored) stored = std::make_shared<ServiceSlot>();
      slot = stored;
    }
    {
      std::unique_lock lock(slot->mutex);
      if (slot->value) {
        return ManagedRef<T>(std::static_pointer_cast<T>(slot->value), cleanup_);
      }
      if (slot->initializing) {
        attempt = slot->attempt;
        slot->ready.wait(lock, [&] { return !slot->initializing; });
        if (slot->value) {
          return ManagedRef<T>(std::static_pointer_cast<T>(slot->value), cleanup_);
        }
        if (slot->completed_attempt == attempt && slot->failure) {
          std::rethrow_exception(slot->failure);
        }
      }
      slot->initializing = true;
      attempt = ++slot->attempt;
      slot->failure = nullptr;
    }
    try {
      auto created = std::invoke(std::forward<Factory>(factory));
      if (!created) throw std::runtime_error("service factory returned null");
      {
        std::unique_lock feature_lock(mutex_);
        std::unique_lock slot_lock(slot->mutex);
        if (state_.load(std::memory_order_acquire) != FeatureState::ACTIVE) {
          slot->initializing = false;
          slot->completed_attempt = attempt;
          slot->failure = std::make_exception_ptr(
              std::runtime_error("feature closed during service construction"));
          slot->ready.notify_all();
          defer_release(std::move(created));
          std::rethrow_exception(slot->failure);
        }
        slot->value = created;
        slot->initializing = false;
        slot->completed_attempt = attempt;
        slot->ready.notify_all();
      }
      return ManagedRef<T>(std::move(created), cleanup_);
    } catch (...) {
      std::unique_lock lock(slot->mutex);
      if (slot->initializing && slot->attempt == attempt) {
        slot->initializing = false;
        slot->completed_attempt = attempt;
        slot->failure = std::current_exception();
        slot->ready.notify_all();
      }
      throw;
    }
  }

 private:
  struct ServiceSlot {
    std::mutex mutex;
    std::condition_variable ready;
    bool initializing = false;
    std::uint64_t attempt = 0;
    std::uint64_t completed_attempt = 0;
    std::shared_ptr<void> value;
    std::exception_ptr failure;
  };

  FeatureSession(SessionId id, std::shared_ptr<RuntimeSession> runtime,
                 std::shared_ptr<DeferredDestruction> cleanup);
  void close(bool runtime_teardown) noexcept;
  void erase_pending(SessionId operation_id) noexcept;

  template <typename T>
  void defer_release(std::shared_ptr<T> value) noexcept {
    if (!value) return;
    auto cleanup = cleanup_;
    if (cleanup && cleanup->submit(
        [value = std::move(value)]() mutable { value.reset(); })) return;
    value.reset();
  }

  SessionId id_;
  std::weak_ptr<RuntimeSession> runtime_;
  std::shared_ptr<DeferredDestruction> cleanup_;
  std::atomic<FeatureState> state_{FeatureState::ACTIVE};
  mutable std::mutex mutex_;
  std::unordered_map<SessionId, std::shared_ptr<PendingOperation>> pending_;
  std::unordered_map<std::string, std::shared_ptr<ServiceSlot>> services_;
};

class FeatureCallScope {
 public:
  explicit FeatureCallScope(std::shared_ptr<FeatureSession> feature) noexcept;
  ~FeatureCallScope();
  FeatureCallScope(const FeatureCallScope &) = delete;
  FeatureCallScope &operator=(const FeatureCallScope &) = delete;

 private:
  std::weak_ptr<FeatureSession> previous_;
};

std::shared_ptr<FeatureSession> current_feature_session() noexcept;

class ProcessServices {
 public:
  using JvmAsyncCompletion =
      std::function<void(void *environment, void *result,
                         std::string error_code, std::string failure)>;

  ProcessServices();
  ~ProcessServices();
  ProcessServices(const ProcessServices &) = delete;
  ProcessServices &operator=(const ProcessServices &) = delete;

  BoundedExecutor &workers() noexcept;
  void configure_worker_threads(
      BoundedExecutor::ThreadInitializer initializer);
  std::shared_ptr<DeferredDestruction> cleanup() const noexcept;
  void set_java_vm(void *java_vm) noexcept;
  void *java_vm() const noexcept;
  SessionId register_jvm_async_completion(JvmAsyncCompletion completion);
  bool discard_jvm_async_completion(SessionId completion_id) noexcept;
  void complete_jvm_async(SessionId completion_id, void *environment,
                          void *result, std::string error_code,
                          std::string failure) noexcept;
  std::size_t thread_count() const noexcept;
  bool retire_runtime(std::shared_ptr<RuntimeSession> runtime) noexcept;
  std::size_t retired_runtime_count() const noexcept;
  bool restart_required() const noexcept;
  void shutdown() noexcept;

 private:
  bool try_schedule_retired_runtime(SessionId id) noexcept;
  bool ensure_retirement_retry_worker() noexcept;
  void retirement_retry_loop() noexcept;
  BoundedExecutor workers_;
  std::shared_ptr<DeferredDestruction> cleanup_;
  std::atomic<void *> java_vm_{nullptr};
  std::mutex jvm_async_mutex_;
  std::unordered_map<SessionId, JvmAsyncCompletion> jvm_async_completions_;
  mutable std::mutex retired_runtime_mutex_;
  std::unordered_map<SessionId, std::shared_ptr<RuntimeSession>> retired_runtimes_;
  std::unordered_set<SessionId> scheduled_retirements_;
  std::condition_variable retirement_ready_;
  std::thread retirement_retry_worker_;
  bool retirement_stopping_ = false;
  std::atomic<bool> restart_required_{false};
};

ProcessServices &process_services() noexcept;

}  // namespace supernote::runtime
