# Generated by supernote_module_generator. Do not edit.
# JNI resolves these classes and members by generated binary names.
# PluginHost casts the generated package through this shared ABI name.
-keep interface com.facebook.react.ReactPackage { *; }
# The runtime deliberately calls PluginHost's parent-loaded SoLoader API.
-keep class com.facebook.soloader.SoLoader { *; }
-keep class com.facebook.soloader.SoSource { *; }
-keep class com.facebook.soloader.DirectorySoSource { *; }
# PluginHost's parent ClassLoader can supply these shared Kotlin ABI classes.
-keep class kotlin.** { *; }
-keep class kotlinx.coroutines.** { *; }
# JNI descriptors include coroutine Job and declared feature types.
-keep,includedescriptorclasses class supernote.generated.runtime.** { *; }
-keep,includedescriptorclasses class supernote.generated.adapters.** { *; }
-keep class com.ziv.snfiletools.** { *; }
