/* Generated by supernote_module_generator. Do not edit. */
export type SupernoteErrorCode =
  | 'RESOURCE_EXHAUSTED'
  | 'CANCELLED'
  | 'FEATURE_CLOSED'
  | 'IMPLEMENTATION_ERROR'
  | 'INTERNAL';

export class SupernoteError extends Error {
  constructor(code: SupernoteErrorCode, message: string);
  readonly code: SupernoteErrorCode;
}

export type SupernoteValidationReason =
  | 'ARITY_MISMATCH'
  | 'TYPE_MISMATCH'
  | 'NOMINAL_MISMATCH'
  | 'MISSING_FIELD'
  | 'INVALID_ENUM'
  | 'OUT_OF_RANGE'
  | 'LIMIT_EXCEEDED';

export interface SupernoteValidationDetails {
  readonly reason: SupernoteValidationReason;
  readonly path: string;
  readonly expected: string;
  readonly actual: string;
}

export type SupernoteTypeError = TypeError & SupernoteValidationDetails;
export type SupernoteRangeError = RangeError & SupernoteValidationDetails;
export type SupernoteValidationResult =
  | {readonly ok: true}
  | {readonly ok: false; readonly error: SupernoteTypeError | SupernoteRangeError};

export interface SupernoteCallable<Arguments extends unknown[], Result> {
  (...args: Arguments): Result;
  accepts(...args: unknown[]): boolean;
  checkArguments(...args: unknown[]): SupernoteValidationResult;
}

export interface SupernoteTypeCompanion<Value> {
  is(value: unknown): value is Value;
  check(value: unknown): SupernoteValidationResult;
}

export type SupernoteFeatureStatus =
  | 'available'
  | 'runtime-unavailable'
  | 'feature-unavailable';

export interface SupernoteNativeObjectInfo {
  readonly type: string;
  readonly originFamily: 'cpp' | 'jvm';
}

export function isFeatureAvailable(): boolean;
export function getFeatureStatus(): SupernoteFeatureStatus;
export function nativeObjectInfo(value: unknown): SupernoteNativeObjectInfo | undefined;
export function isSupernoteTypeError(value: unknown): value is SupernoteTypeError;
export function isSupernoteRangeError(value: unknown): value is SupernoteRangeError;

export interface SnfiletoolsFeature {
  bitmapMatches: SupernoteCallable<[path: string, patternPath: string, pageKey: string], Promise<boolean>>;
  clearNoteFileCache: SupernoteCallable<[path: string, page: number], Promise<boolean>>;
  copyPageTotalPath: SupernoteCallable<[path: string, sourcePath: string, backupPath: string, pageKey: string, sourcePageKey: string], Promise<string>>;
  encodeExportedBitmap: SupernoteCallable<[pngPath: string, rlePath: string, width: number, height: number], Promise<string>>;
  getSize: SupernoteCallable<[path: string], Promise<bigint>>;
  getTotalPathTestState: SupernoteCallable<[pluginDirectory: string], Promise<string>>;
  greet: SupernoteCallable<[name: string], string>;
  greetFromJvm: SupernoteCallable<[name: string], string>;
  requestNoteRedraw: SupernoteCallable<[], Promise<string>>;
  restoreTestNote: SupernoteCallable<[path: string, backupPath: string], Promise<void>>;
  setJournalDirectory: SupernoteCallable<[path: string], Promise<void>>;
  setTotalPathTestState: SupernoteCallable<[pluginDirectory: string, state: string], Promise<void>>;
  testBitmapReplace: SupernoteCallable<[path: string, patternPath: string, backupPath: string, pageKey: string], Promise<string>>;
  testBitmapUnchanged: SupernoteCallable<[path: string, referencePath: string, pageKey: string], Promise<boolean>>;
  testMetadataEditAndRestore: SupernoteCallable<[path: string, backupPath: string], Promise<string>>;
  testReopenSnapshot: SupernoteCallable<[path: string, snapshotPath: string], Promise<void>>;
  testTotalPathCopy: SupernoteCallable<[path: string, sourcePath: string, backupPath: string, pageKey: string], Promise<string>>;
  testTotalPathEdit: SupernoteCallable<[path: string, backupPath: string], Promise<string>>;
  testTotalPathPaste: SupernoteCallable<[path: string, sourcePath: string, backupPath: string, pageKey: string], Promise<string>>;
  testTotalPathUnchanged: SupernoteCallable<[path: string, referencePath: string, pageKey: string], Promise<boolean>>;
  waitForNoteRefresh: SupernoteCallable<[milliseconds: number], Promise<void>>;
}

declare const feature: SnfiletoolsFeature;
export default feature;
