// Generated by supernote_module_generator. Do not edit.
package supernote.generated.packages.feature_7e680f69f87879eb;

public final class JvmRegistration {
  private JvmRegistration() {}

  public static String featureId() { return "supernote:feature:7e680f69f87879eb"; }
  public static String packageName() { return "snfiletools"; }
  public static String publicName() { return "Snfiletools"; }
  public static String cmakeTarget() { return "supernote_feature_7e680f69f87879eb"; }
}
