// Generated by supernote_module_generator. Do not edit.
#pragma once

#include "runtime_services.hpp"

#include <jsi/jsi.h>

#include <cstddef>
#include <functional>
#include <list>
#include <memory>
#include <stdexcept>
#include <string>
#include <string_view>
#include <type_traits>
#include <utility>
#include <vector>

namespace supernote::runtime {

class ManagedAnyRef final {
 public:
  ManagedAnyRef() = default;

  template <typename T>
  ManagedAnyRef(
      std::shared_ptr<T> value,
      std::shared_ptr<DeferredDestruction> cleanup)
      : value_(std::move(value)), cleanup_(std::move(cleanup)) {}

  ManagedAnyRef(const ManagedAnyRef &) = default;
  ManagedAnyRef &operator=(const ManagedAnyRef &other) {
    if (this == &other) return *this;
    reset();
    value_ = other.value_;
    cleanup_ = other.cleanup_;
    return *this;
  }
  ManagedAnyRef(ManagedAnyRef &&) noexcept = default;
  ManagedAnyRef &operator=(ManagedAnyRef && other) noexcept {
    if (this == &other) return *this;
    reset();
    value_ = std::move(other.value_);
    cleanup_ = std::move(other.cleanup_);
    return *this;
  }
  ~ManagedAnyRef() { reset(); }

  explicit operator bool() const noexcept { return static_cast<bool>(value_); }

  void reset() noexcept {
    auto value = std::move(value_);
    auto cleanup = cleanup_;
    cleanup_.reset();
    if (!value) return;
    if (cleanup && cleanup->submit(
        [value = std::move(value)]() mutable { value.reset(); })) return;
    value.reset();
  }

 private:
  std::shared_ptr<void> value_;
  std::shared_ptr<DeferredDestruction> cleanup_;
};

class CppObjectHandleBase : public facebook::jsi::HostObject {
 public:
  ~CppObjectHandleBase() override = default;
  [[nodiscard]] virtual std::string_view type_id() const noexcept = 0;
  [[nodiscard]] virtual const void *native_address() const noexcept = 0;
};

template <typename T>
class CppObjectHandle : public CppObjectHandleBase {
 public:
  CppObjectHandle(std::string type_id, ManagedRef<T> instance)
      : type_id_(std::move(type_id)), instance_(std::move(instance)) {
    if (type_id_.empty() || !instance_) {
      throw std::invalid_argument(
          "a C++ object handle requires nominal identity and an instance");
    }
  }

  [[nodiscard]] std::string_view type_id() const noexcept override {
    return type_id_;
  }

  [[nodiscard]] const void *native_address() const noexcept override {
    return instance_.get();
  }

  [[nodiscard]] ManagedRef<T> managed_ref() const { return instance_; }
  [[nodiscard]] const std::shared_ptr<T> &shared_ref() const noexcept {
    return instance_.shared_ref();
  }

 private:
  std::string type_id_;
  ManagedRef<T> instance_;
};

class CppObjectIdentity final {
 public:
  template <typename T>
  static CppObjectIdentity from(
      std::string type_id, const std::shared_ptr<T> &instance) {
    if (type_id.empty() || !instance) {
      throw std::invalid_argument(
          "C++ object identity requires nominal identity and an instance");
    }
    return CppObjectIdentity(
        std::move(type_id), std::weak_ptr<void>(instance), instance.get());
  }

  template <typename T>
  [[nodiscard]] bool matches(
      std::string_view type_id, const std::shared_ptr<T> &instance) const {
    if (!instance || type_id_ != type_id || address_ != instance.get()) {
      return false;
    }
    const std::weak_ptr<void> candidate(instance);
    const std::owner_less<std::weak_ptr<void>> less;
    return !less(owner_, candidate) && !less(candidate, owner_);
  }

  [[nodiscard]] bool expired() const noexcept { return owner_.expired(); }
  [[nodiscard]] std::string_view type_id() const noexcept { return type_id_; }
  [[nodiscard]] const void *address() const noexcept { return address_; }
  [[nodiscard]] bool same_address_and_type(
      std::string_view type_id, const void *address) const noexcept {
    return type_id_ == type_id && address_ == address;
  }

 private:
  CppObjectIdentity(
      std::string type_id, std::weak_ptr<void> owner, const void *address)
      : type_id_(std::move(type_id)),
        owner_(std::move(owner)),
        address_(address) {}

  std::string type_id_;
  std::weak_ptr<void> owner_;
  const void *address_;
};

class CppObjectRegistry final
    : public std::enable_shared_from_this<CppObjectRegistry> {
 public:
  explicit CppObjectRegistry(std::shared_ptr<DeferredDestruction> cleanup)
      : cleanup_(std::move(cleanup)) {
    if (!cleanup_) {
      throw std::invalid_argument(
          "the C++ object registry requires deferred destruction");
    }
  }

  CppObjectRegistry(const CppObjectRegistry &) = delete;
  CppObjectRegistry &operator=(const CppObjectRegistry &) = delete;

  template <typename T, typename Factory>
  facebook::jsi::Object wrap(
      facebook::jsi::Runtime &runtime,
      std::string_view type_id,
      std::shared_ptr<T> instance,
      Factory &&factory) {
    assert_runtime(runtime);
    if (!instance) {
      throw std::invalid_argument("a native object result cannot be null");
    }
    for (auto current = entries_.begin(); current != entries_.end();) {
      if (current->identity.expired()) {
        current = entries_.erase(current);
        continue;
      }
      if (!current->identity.matches(type_id, instance)) {
        if (current->identity.same_address_and_type(type_id, instance.get())) {
          throw std::logic_error(
              "conflicting C++ shared owners for one live native address");
        }
        ++current;
        continue;
      }
      auto locked = current->javascript.lock(runtime);
      if (locked.isObject()) return locked.getObject(runtime);
      current = entries_.erase(current);
      break;
    }

    auto identity = CppObjectIdentity::from(std::string(type_id), instance);
    auto managed = ManagedRef<T>(std::move(instance), cleanup_);
    auto host = std::invoke(
        std::forward<Factory>(factory), std::move(managed));
    static_assert(
        std::is_convertible_v<decltype(host),
                              std::shared_ptr<facebook::jsi::HostObject>>);
    auto object = facebook::jsi::Object::createFromHostObject(
        runtime, std::move(host));
    entries_.emplace_back(
        std::move(identity), facebook::jsi::WeakObject(runtime, object));
    return object;
  }

  void purge(facebook::jsi::Runtime &runtime) {
    assert_runtime(runtime);
    for (auto current = entries_.begin(); current != entries_.end();) {
      if (current->identity.expired() ||
          !current->javascript.lock(runtime).isObject()) {
        current = entries_.erase(current);
      } else {
        ++current;
      }
    }
  }

  [[nodiscard]] std::size_t size_for_testing() const noexcept {
    return entries_.size();
  }

 private:
  struct Entry final {
    Entry(CppObjectIdentity identity, facebook::jsi::WeakObject javascript)
        : identity(std::move(identity)), javascript(std::move(javascript)) {}
    CppObjectIdentity identity;
    facebook::jsi::WeakObject javascript;
  };

  void assert_runtime(facebook::jsi::Runtime &runtime) {
    if (runtime_ == nullptr) {
      runtime_ = &runtime;
    } else if (runtime_ != &runtime) {
      throw std::logic_error(
          "a C++ object registry cannot cross JavaScript runtimes");
    }
  }

  std::shared_ptr<DeferredDestruction> cleanup_;
  facebook::jsi::Runtime *runtime_ = nullptr;
  std::list<Entry> entries_;
};

class CppObjectRegistryOwner final : public facebook::jsi::HostObject {
 public:
  explicit CppObjectRegistryOwner(std::shared_ptr<CppObjectRegistry> registry)
      : registry_(std::move(registry)) {
    if (!registry_) throw std::invalid_argument("object registry is required");
  }

  [[nodiscard]] const std::shared_ptr<CppObjectRegistry> &registry() const {
    return registry_;
  }

 private:
  std::shared_ptr<CppObjectRegistry> registry_;
};

inline std::string cpp_object_type_id(
    facebook::jsi::Runtime &runtime,
    const facebook::jsi::Value &value) {
  if (!value.isObject()) return {};
  auto object = value.getObject(runtime);
  if (!object.isHostObject<CppObjectHandleBase>(runtime)) return {};
  return std::string(
      object.getHostObject<CppObjectHandleBase>(runtime)->type_id());
}

template <typename T>
ManagedRef<T> try_extract_cpp_object(
    facebook::jsi::Runtime &runtime,
    const facebook::jsi::Value &value,
    std::string_view expected_type_id) {
  if (!value.isObject()) return {};
  auto object = value.getObject(runtime);
  if (!object.isHostObject<CppObjectHandleBase>(runtime)) return {};
  auto base = object.getHostObject<CppObjectHandleBase>(runtime);
  if (base->type_id() != expected_type_id) return {};
  auto typed = std::dynamic_pointer_cast<CppObjectHandle<T>>(base);
  return typed ? typed->managed_ref() : ManagedRef<T>{};
}

}  // namespace supernote::runtime
