// Generated by supernote_module_generator. Do not edit.
#pragma once

#include <stdexcept>
#include <string>
#include <utility>
#include <variant>

namespace supernote {

enum class ErrorCode {
  RESOURCE_EXHAUSTED,
  CANCELLED,
  FEATURE_CLOSED,
  IMPLEMENTATION_ERROR,
  INTERNAL,
};

class Error final : public std::runtime_error {
 public:
  Error(ErrorCode code, std::string message)
      : std::runtime_error(std::move(message)), code_(code) {}
  ErrorCode code() const noexcept { return code_; }

 private:
  ErrorCode code_;
};

template <typename T>
class Result final {
 public:
  static Result success(T value) {
    return Result(std::in_place_index<0>, std::move(value));
  }
  static Result failure(Error error) {
    return Result(std::in_place_index<1>, std::move(error));
  }
  explicit operator bool() const noexcept { return value_.index() == 0; }
  T &value() & { return std::get<0>(value_); }
  const T &value() const & { return std::get<0>(value_); }
  T &&value() && { return std::get<0>(std::move(value_)); }
  Error &error() & { return std::get<1>(value_); }
  const Error &error() const & { return std::get<1>(value_); }

 private:
  template <std::size_t Index, typename Value>
  Result(std::in_place_index_t<Index> index, Value value)
      : value_(index, std::move(value)) {}
  std::variant<T, Error> value_;
};

template <>
class Result<void> final {
 public:
  static Result success() { return Result(); }
  static Result failure(Error error) { return Result(std::move(error)); }
  explicit operator bool() const noexcept { return success_; }
  void value() const {
    if (!success_) throw std::logic_error("Supernote result has no value");
  }
  Error &error() & { return error_; }
  const Error &error() const & { return error_; }

 private:
  Result() : success_(true), error_(ErrorCode::INTERNAL, "no error") {}
  explicit Result(Error error) : success_(false), error_(std::move(error)) {}
  bool success_;
  Error error_;
};

}  // namespace supernote
