// Generated by supernote_module_generator. Do not edit.
#pragma once

#include <cstddef>
#include <cstdint>
#include <functional>
#include <string>
#include <vector>

#include <supernote/runtime.hpp>


namespace supernote::internal::Snfiletools {



}  // namespace supernote::internal::Snfiletools
