// Generated by supernote_module_generator. Do not edit.
#include <internal.hpp>

#include "runtime_services.hpp"


#include <android/log.h>

#include <exception>
#include <memory>
#include <stdexcept>
#include <tuple>
#include <utility>



namespace supernote::internal::Snfiletools {
namespace {

constexpr char kInternalLogTag[] = "SupernoteModuleInternal";

std::shared_ptr<supernote::runtime::FeatureSession> require_feature() {
  auto feature = supernote::runtime::current_feature_session();
  if (!feature ||
      feature->state() != supernote::runtime::FeatureState::ACTIVE) {
    throw supernote::Error(
        supernote::ErrorCode::FEATURE_CLOSED, "feature is closed");
  }
  return feature;
}

template <typename Callback, typename Result>
void deliver_callback(Callback &callback, Result result) noexcept {
  try {
    callback(std::move(result));
  } catch (const std::exception &error) {
    __android_log_print(
        ANDROID_LOG_ERROR, kInternalLogTag,
        "internal completion callback threw: %s", error.what());
  } catch (...) {
    __android_log_print(
        ANDROID_LOG_ERROR, kInternalLogTag,
        "internal completion callback threw an unknown exception");
  }
}

}  // namespace



}  // namespace supernote::internal::Snfiletools
