// Generated by supernote_module_generator. Do not edit.
#include "package_registration.hpp"

#include <memory>

namespace facebook::jsi {
class Object;
class Runtime;
}
namespace supernote::runtime {
class FeatureSession;
}

namespace supernote::generated::feature_7e680f69f87879eb {
void register_feature(
    facebook::jsi::Runtime &runtime,
    facebook::jsi::Object &feature_registry,
    const std::shared_ptr<supernote::runtime::FeatureSession> &feature_session);
}
namespace supernote::generated::jvm_feature_7e680f69f87879eb {
void register_jvm_feature(
    facebook::jsi::Runtime &runtime,
    facebook::jsi::Object &feature_registry,
    const std::shared_ptr<supernote::runtime::FeatureSession> &feature_session);
}

namespace {
constexpr SupernotePackageRegistration kRegistration{
    "supernote:feature:7e680f69f87879eb",
    "snfiletools",
    "Snfiletools",
    "supernote_feature_7e680f69f87879eb",
};
}  // namespace

extern "C" const SupernotePackageRegistration *supernote_package_registration_7e680f69f87879eb() noexcept {
  return &kRegistration;
}

extern "C" void supernote_package_install_native_7e680f69f87879eb(
    void *runtime, void *feature_registry, const void *feature_session) {
  supernote::generated::feature_7e680f69f87879eb::register_feature(
      *static_cast<facebook::jsi::Runtime *>(runtime),
      *static_cast<facebook::jsi::Object *>(feature_registry),
      *static_cast<const std::shared_ptr<supernote::runtime::FeatureSession> *>(
          feature_session));
}

extern "C" void supernote_package_install_jvm_7e680f69f87879eb(
    void *runtime, void *feature_registry, const void *feature_session) {
  supernote::generated::jvm_feature_7e680f69f87879eb::register_jvm_feature(
      *static_cast<facebook::jsi::Runtime *>(runtime),
      *static_cast<facebook::jsi::Object *>(feature_registry),
      *static_cast<const std::shared_ptr<supernote::runtime::FeatureSession> *>(
          feature_session));
}
