// Generated by supernote_module_generator. Do not edit.
#pragma once

struct SupernotePackageRegistration {
  const char *feature_id;
  const char *package_name;
  const char *public_name;
  const char *cmake_target;
};

extern "C" const SupernotePackageRegistration *supernote_package_registration_7e680f69f87879eb() noexcept;
extern "C" void supernote_package_install_native_7e680f69f87879eb(
    void *runtime, void *feature_registry, const void *feature_session);
extern "C" void supernote_package_install_jvm_7e680f69f87879eb(
    void *runtime, void *feature_registry, const void *feature_session);
